modLoader="javafml"
loaderVersion="[43,)"
license="All rights reserved"
issueTrackerURL="https://github.com/cazmat/SocietyMC/issues"
[[mods]]
    modId="societycore"
    version="${file.jarVersion}"
    displayName="SocietyCore"
    updateJSONURL="https://raw.githubusercontent.com/cazmat/SocietyMC/main/updates.json"
    displayURL="https://mlutz.us" #optional
    authors="Cazmat"
    description='''
        Core mod for SocietyMC community server
    '''
[[dependencies.societycore]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.societycore]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"
